[package]
name = "embedder"
version = "0.1.0"
edition = "2021"
author = "theart42"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.6.6"
winapi = "0.3.9"
